package com.kimlic.utils

enum class AppDoc(val type: String) {
    PASSPORT("PASSPORT"),
    ID_CARD("ID_CARD"),
    DRIVERS_LICENSE("DRIVERS_LICENSE"),
    RESIDENCE_PERMIT_CARD("RESIDENCE_PERMIT_CARD"),

    SOCIAL_SECURITY_CARD("SOCIAL_SECURITY_CARD"),
    BIRTH_CERTIFICATE("BIRTH_CERTIFICATE")
}